# Generated by Django 6.0 on 2025-12-16 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('ano', models.IntegerField()),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ALUGADO', 'Alugado'), ('MANUTENCAO', 'Em Manutenção')], default='DISPONIVEL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alugueis_realizados', to=settings.AUTH_USER_MODEL)),
                ('perfil_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='accounts.perfilcliente')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='core.carro')),
            ],
        ),
    ]
